#!/bin/bash

############################################
# install.sh                               #
# Junhyeok Ahn ( junhyeokahn91@gmail.com ) #
############################################

cd $(dirname $BASH_SOURCE)
BASE=$(pwd)

if [ "$(uname)" == "Darwin" ]; then
    for rc in bashrc bash_profile bash_prompt vimrc tmux.conf; do
      mkdir -pv bak
      [ -e ~/.$rc ] && mv -v ~/.$rc bak/.$rc
      ln -sfv $BASE/$rc ~/.$rc
    done

    echo 'eval "$(/opt/homebrew/bin/brew shellenv)"' >> ~/.bashrc
    echo 'export BASH_SILENCE_DEPRECATION_WARNING=1' >> ~/.bashrc
    echo 'export PATH="/opt/homebrew/bin:$PATH"' >> ~/.bashrc

    #### put this at the last of conda initialize if you use conda ####
    # [[ -z $TMUX ]] || conda deactivate; conda activate base

    [ -z "$(which brew)" ] &&
      ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"

    echo "Updating homebrew"
    brew install tmux vim reattach-to-user-namespace ctags-exuberant cmake clang-format llvm

    xcode-select --install

    source ./install-vim

elif [ "$(expr substr $(uname -s) 1 5)" == "Linux" ]; then

    for rc in vimrc bash_profile bash_prompt tmux.conf; do
      mkdir -pv bak
      [ -e ~/.$rc ] && mv -v ~/.$rc bak/.$rc
      ln -sfv $BASE/$rc ~/.$rc
    done

    echo 'setxkbmap -option caps:ctrl_modifier' >> ~/.bashrc

    sudo apt-get -y install tmux curl vim ctags clang-format clangd-9

    source ./install-vim
    source ~/dotfiles/seoul256-gnome-terminal/seoul256-dark.sh

else
    echo "[error] os not detected"
fi
