#!/bin/bash

############################################
# install.sh                               #
# Junhyeok Ahn ( junhyeokahn91@gmail.com ) #
############################################

cd $(dirname $BASH_SOURCE)
BASE=$(pwd)

for rc in bashrc bash_profile bash_prompt vimrc tmux.conf; do
  mkdir -pv bak
  [ -e ~/.$rc ] && mv -v ~/.$rc bak/.$rc
  ln -sfv $BASE/$rc ~/.$rc
done

if [ $(uname -s) = 'Darwin' ]; then
  # Homebrew
  [ -z "$(which brew)" ] &&
    ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"

  echo "Updating homebrew"
  brew install git tmux vim reattach-to-user-namespace ctags-exuberant cmake clang-format

  xcode-select --install

fi

source ./install-vim
