#!/bin/bash

############################################
# install-bash                             #
# Junhyeok Ahn ( junhyeokahn91@gmail.com ) #
############################################

cd $(dirname $BASH_SOURCE)
BASE=$(pwd)

for rc in bashrc bash_profile bash_prompt vimrc tmux.conf; do
  mkdir -pv bak
  [ -e ~/.$rc ] && mv -v ~/.$rc bak/.$rc
  ln -sfv $BASE/$rc ~/.$rc
done

source ./install-vim

if [ "$(uname)" == "Darwin" ]; then

    echo 'eval "$(/opt/homebrew/bin/brew shellenv)"' >> ~/.bashrc
    echo 'export BASH_SILENCE_DEPRECATION_WARNING=1' >> ~/.bashrc

    #### put this at the last of conda initialize if you use conda ####
    # [[ -z $TMUX ]] || conda deactivate; conda activate base


elif [ "$(expr substr $(uname -s) 1 5)" == "Linux" ]; then

    echo 'setxkbmap -option caps:ctrl_modifier' >> ~/.bashrc

    source ~/dotfiles/seoul256-gnome-terminal/seoul256-dark.sh

else
    echo "[error] os not detected"
fi
