#!/bin/bash

############################################
# .install-vim                             #
# Junhyeok Ahn ( junhyeokahn91@gmail.com ) #
############################################

cd $(dirname $BASH_SOURCE)
BASE=$(pwd)

export GIT_SSL_NO_VERIFY=true
mkdir -p ~/.vim/autoload
curl --insecure -fLo ~/.vim/autoload/plug.vim https://raw.github.com/junegunn/vim-plug/master/plug.vim

mv -v ~/.vimrc ~/.vimrc.old 2> /dev/null
ln -sf $BASE/vimrc ~/.vimrc

vim +PlugInstall +qall

for snip in cpp.snippets python.snippets bib.snippets markdown.snippets texmath.snippets c.snippets vim.snippets tex.snippets; do
  rm ~/.vim/plugged/vim-snippets/UltiSnips/$snip
  ln -sfv $BASE/snippets/$snip ~/.vim/plugged/vim-snippets/UltiSnips/$snip
done
