############################################
# .tmux_conf                               #
# Junhyeok Ahn ( junhyeokahn91@gmail.com ) #
############################################

################
# Main Setting #
################

unbind-key C-b
set-option -g prefix C-a

set -g base-index 1

set -sg escape-time 0
set-option -g repeat-time 500

set -g history-limit 10240

set-option -g default-terminal "screen-256color"
set-option -ga terminal-overrides ",xterm-256color:Tc"

set -g status-keys vi
setw -g mode-keys vi

setw -g mouse on

set-option -g renumber-windows on
set-window-option -g automatic-rename on
set-option -g set-titles on

bind-key v split-window -h
bind-key s split-window -v
bind-key J resize-pane -D 5
bind-key K resize-pane -U 5
bind-key H resize-pane -L 5
bind-key L resize-pane -R 5

bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

if-shell "uname | grep -q Darwin" {
  bind-key -T copy-mode-vi 'y' send -X copy-pipe-and-cancel 'reattach-to-user-namespace pbcopy'
  bind-key -T copy-mode-vi Enter send -X copy-pipe-and-cancel 'reattach-to-user-namespace pbcopy'
} {
  bind-key -T copy-mode-vi 'y' send -X copy-pipe-and-cancel 'xclip -in -selection clipboard'
  bind-key -T copy-mode-vi Enter send -X copy-pipe-and-cancel 'xclip -in -selection clipboard'
}

bind -T copy-mode-vi Enter send-keys -X copy-pipe-and-cancel "xclip -i -f -selection primary | xclip -i -selection clipboard"

bind r source-file ~/.tmux.conf \; display-message "Reloaded!"

run-shell "~/dotfiles/theme/nord-tmux/nord.tmux"
